import{a as q,S as E,i as c}from"./assets/vendor-Db2TdIkw.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const S="https://pixabay.com/api/",v="49423547-3925a10a81c3177a913fbde2f",P=15;async function m(t,r=1){try{const a=await q.get(S,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",per_page:P,page:r,safesearch:!0}});if(a.data.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return{images:a.data.hits,totalHits:a.data.totalHits}}catch(a){throw new Error(a.message)}}const H=new E(".gallery a");function f(t,r){const a=t.map(({webformatURL:i,largeImageURL:e,tags:o,likes:s,views:b,comments:w,downloads:L})=>`<li class="gallery-item">
          <a href="${e}" target="_blank">
            <img class="gallery-image" src="${i}" alt="${o}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${s}</p>
            <p><b>Views</b> ${b}</p>
            <p><b>Comments</b> ${w}</p>
            <p><b>Downloads</b> ${L}</p>
          </div>
        </li>`).join("");r.insertAdjacentHTML("beforeend",a),H.refresh()}function $(t){t.innerHTML=""}function g(){document.querySelector(".loader").style.display="flex"}function p(){document.querySelector(".loader").style.display="none"}const x=document.querySelector(".form"),u=document.querySelector(".gallery");document.querySelector(".loader");const d=document.querySelector(".load-more");let l="",n=1,h=0;const y=15;x.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.elements["search-text"].value.trim(),!l){c.warning({title:"Warning",message:"Enter a search query!"});return}$(u),d.style.display="none",g();try{n=1;const{images:r,totalHits:a}=await m(l,n);h=a,f(r,u),r.length>=y&&(d.style.display="block")}catch(r){c.error({title:"Error",message:r.message})}finally{p()}});d.addEventListener("click",async()=>{n+=1,g();try{const{images:t}=await m(l,n);f(t,u,!0);const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),(t.length<y||n*y>=h)&&(d.style.display="none",c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch(t){c.error({title:"Error",message:t.message})}finally{p()}});
//# sourceMappingURL=index.js.map
