import{a as L,S as q,i as c}from"./assets/vendor-Db2TdIkw.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const E="https://pixabay.com/api/",S="49423547-3925a10a81c3177a913fbde2f",H=15;async function m(t,r=1){try{const o=await L.get(E,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",per_page:H,page:r,safesearch:!0}});if(o.data.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return{images:o.data.hits,totalHits:o.data.totalHits}}catch(o){throw new Error(o.message)}}const v=new q(".gallery a");function f(t,r){const o=t.map(({webformatURL:n,largeImageURL:e,tags:a,likes:s,views:h,comments:b,downloads:w})=>`<li class="gallery-item">
          <a href="${e}" target="_blank">
            <img class="gallery-image" src="${n}" alt="${a}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${s}</p>
            <p><b>Views</b> ${h}</p>
            <p><b>Comments</b> ${b}</p>
            <p><b>Downloads</b> ${w}</p>
          </div>
        </li>`).join("");r.insertAdjacentHTML("beforeend",o),v.refresh()}function P(t){t.innerHTML=""}function g(){document.querySelector(".loader").style.display="flex"}function p(){document.querySelector(".loader").style.display="none"}const $=document.querySelector(".form"),u=document.querySelector(".gallery");document.querySelector(".loader");const d=document.querySelector(".load-more");let l="",i=1,y=0;const x=15;$.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.elements["search-text"].value.trim(),!l){c.warning({title:"Warning",message:"Enter a search query!"});return}P(u),d.style.display="none",g();try{i=1;const{images:r,totalHits:o}=await m(l,i);y=o,f(r,u),d.style.display="block"}catch(r){c.error({title:"Error",message:r.message})}finally{p()}});d.addEventListener("click",async()=>{i+=1,g();try{const{images:t,totalHits:r}=await m(l,i);y=r,f(t,u,!0);const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),i*x>=y&&(d.style.display="none",c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch(t){c.error({title:"Error",message:t.message})}finally{p()}});
//# sourceMappingURL=index.js.map
